from numpy import *
a = arange(8).reshape(2,4)
print(a)
print('----------------')
b = hsplit(a,4)
print(b)
print('----------------')
print(b[0].shape)
print('----------------')
print(b[0])
print('----------------')
print(b[2])
print('----------------')
print(hsplit(a,2))
